"""Add is_pinned to chat sessions

Revision ID: 085f7a62e35f
Revises: 573301c9a45e
Create Date: 2026-06-11 11:34:33.611289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '085f7a62e35f'
down_revision: Union[str, Sequence[str], None] = '573301c9a45e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('is_pinned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'is_pinned')
    # ### end Alembic commands ###
