"""Add name column and change admin to lawyer

Revision ID: 46165de62698
Revises: c792a185ea79
Create Date: 2026-06-10 11:18:11.378858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46165de62698'
down_revision: Union[str, Sequence[str], None] = 'c792a185ea79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.execute("UPDATE users SET name = 'Unknown' WHERE name IS NULL")
    op.alter_column('users', 'name', nullable=False)
    
    # Rename enum value
    op.execute("ALTER TYPE userrole RENAME VALUE 'admin' TO 'lawyer'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
