"""Refactor feedback to separate table

Revision ID: 573301c9a45e
Revises: 861ac6f98c5a
Create Date: 2026-06-11 11:29:43.614528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '573301c9a45e'
down_revision: Union[str, Sequence[str], None] = '861ac6f98c5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('lawyer_id', sa.Integer(), nullable=False),
    sa.Column('is_good', sa.Boolean(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['lawyer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_id'), 'feedbacks', ['id'], unique=False)
    op.create_index(op.f('ix_feedbacks_message_id'), 'feedbacks', ['message_id'], unique=False)
    op.create_index(op.f('ix_feedbacks_mufti_id'), 'feedbacks', ['lawyer_id'], unique=False)
    op.drop_column('chat_messages', 'is_good')
    op.drop_column('chat_messages', 'feedback_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('feedback_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('chat_messages', sa.Column('is_good', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_feedbacks_mufti_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_message_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
